/**
 * Crea 6 articulos nuevos en Sanity para el blog de PixelArch
 * Uso: node node_modules/tsx/dist/cli.mjs src/scripts/seed-articulos.ts
 * Requiere SANITY_API_TOKEN en .env.local
 */
import { config } from "dotenv"
config({ path: ".env.local" })

import { createClient } from "@sanity/client"
import sharp from "sharp"
import { coverSvg } from "./covers"

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || "production",
  apiVersion: "2024-01-01",
  token: process.env.SANITY_API_TOKEN,
  useCdn: false,
})

interface ArticuloSeed {
  slug: string
  titulo: string
  descripcion: string
  fecha: string
  tags: string[]
  meta_title: string
  meta_description: string
  contenido: string[]
}

const ARTICULOS: ArticuloSeed[] = [
  {
    slug: "landing-pages-que-convierten",
    titulo: "Landing pages que convierten: la estructura que usamos en cada proyecto",
    descripcion: "Una landing bonita no vende. Te mostramos la estructura exacta que usamos en cada proyecto para convertir visitas en clientes.",
    fecha: "2026-09-09",
    tags: ["Landing pages", "Conversión", "SEO", "Diseño web"],
    meta_title: "Landing pages que convierten: estructura y metodología | PixelArch",
    meta_description: "La estructura que usamos en cada landing page: hero, prueba social, beneficios, FAQ y CTA. Método probado para convertir visitas en clientes.",
    contenido: [
      "La página de inicio de la mayoría de las pymes cuenta la historia del emprendedor: cómo empezó, qué le apasiona, cuánto le costó. Esa página no vende. La persona que la visita llega con una pregunta en la cabeza ('¿este producto resuelve mi problema?') y se va sin respuesta, porque el texto le contó otra cosa.",
      "Una landing page efectiva no es más linda que una web tradicional: está estructurada para responder la pregunta del visitante en el orden exacto en que la hace. Esa estructura se puede repetir en cualquier proyecto, y es la que usamos en PixelArch.",
      "H2: La estructura que repetimos en cada landing",
      "El orden importa más que el diseño. En cada landing que construimos, la información aparece en esta secuencia:",
      "BULLET:Hero con una sola promesa: qué es, para quién, y una sola acción posible. Un visitante que lee tres ofertas distintas no hace ninguna.",
      "BULLET:Prueba social cerca del hero: números, logos, clientes. La prueba social no es un adorno del final; es lo que sostiene la promesa inicial.",
      "BULLET:Tres beneficios concretos, no tres características. 'Respondemos en menos de 24hs' vende más que 'Atención personalizada'.",
      "BULLET:Cómo funciona en pasos: desarmar el proceso en tres o cuatro pasos elimina el miedo a lo desconocido.",
      "BULLET:Preguntas frecuentes antes del formulario: las dudas que frenan a alguien justo antes de escribir ('¿cómo cancelo?', '¿en qué moneda cobran?') tienen que estar respondidas ahí.",
      "BULLET:Un solo CTA principal, repetido: el botón de acción aparece al menos tres veces, siempre con el mismo texto.",
      "H2: La velocidad también es conversión",
      "Una landing que tarda cuatro segundos en cargar pierde más de la mitad de los visitantes en móviles. Los Core Web Vitals que Google mide (velocidad de carga, estabilidad visual, respuesta a interacciones) son los mismos que el visitante percibe como 'esta página anda bien' o 'esta página anda mal'.",
      "Por eso en PixelArch cada landing se construye con métricas de rendimiento en la mesa desde el día uno: imágenes optimizadas, fuentes que no bloquean la renderización y código sin librerías innecesarias. No es una mejora posterior: es parte del proceso.",
      "H2: Qué medimos después de publicar",
      "Publicar es el punto de partida, no la meta. Las dos semanas siguientes a cada lanzamiento medimos:",
      "BULLET:Qué sección ve la gente y en cuál se queda (mapa de scroll y de calor).",
      "BULLET:Qué botones reciben clics y cuáles nadie toca.",
      "BULLET:Qué formularios se envían y cuáles se abandonan a mitad de camino.",
      "BULLET:De dónde viene el tráfico que sí convierte, para invertir más ahí.",
      "Con esos datos ajustamos el texto y el orden de las secciones. Las mejores conversiones aparecen después de la segunda o tercera iteración, no en el primer diseño.",
      "H2: Cómo arrancar",
      "Si tu página actual no convierte, el primer paso no es rediseñarla entera: es medir dónde se pierde la gente y corregir el mensaje. En PixelArch regalamos una auditoría exprés de landing pages — velocidad, SEO, conversión y seguridad — para que sepas exactamente qué cambiar primero y qué puede esperar.",
    ],
  },
  {
    slug: "que-es-un-agente-de-ia",
    titulo: "Qué es un agente de IA (y qué puede hacer por tu negocio)",
    descripcion: "Chatbots que responden, agentes que actúan: la diferencia que cambia cómo tu negocio usa la inteligencia artificial. Explicado sin tecnicismos.",
    fecha: "2026-09-09",
    tags: ["IA", "Agentes", "Automatización", "Negocios"],
    meta_title: "Qué es un agente de IA y qué puede hacer por tu negocio | PixelArch",
    meta_description: "La diferencia entre un chatbot y un agente de IA, con ejemplos concretos por rubro: qué hacen, qué necesitan y cuánto cuesta ponerlos a trabajar.",
    contenido: [
      "Los chatbots resolvieron una parte del problema: pueden responder preguntas frecuentes las 24 horas. Pero se quedan cortos en el siguiente paso. Un cliente no solo pregunta: también quiere que algo pase. Que se le genere una factura, que se le confirme un turno, que se le reembolse un envío.",
      "Ahí aparece la diferencia entre un chatbot y un agente de IA. El chatbot responde. El agente, además, actúa.",
      "H2: La diferencia en una frase",
      "Un chatbot te dice qué hacer. Un agente de IA lo hace por vos: analiza la situación, decide qué paso corresponde y ejecuta la acción conectándose con tus herramientas — el sistema de facturación, el calendario, el correo, la base de clientes.",
      "Para decirlo simple: si un cliente escribe 'perdí el acceso a mi cuenta', el chatbot responde 'te paso con un humano'. El agente verifica la identidad, genera un link de recuperación y lo envía, mientras te avisa a vos por Slack que el incidente quedó resuelto.",
      "H2: Qué tareas son candidatas reales",
      "No todo sirve para un agente. Los mejores candidatos comparten tres características: son repetitivos, siguen reglas claras y hoy ocupan horas de una persona. Ejemplos concretos:",
      "BULLET:Atención al cliente que termina en acciones: reembolsos, cambios de plan, recuperación de cuentas.",
      "BULLET:Clasificación y respuesta de correos: separa lo urgente de lo informativo, redacta borradores y los deja listos para aprobar.",
      "BULLET:Reportes periódicos: junta datos de ventas, los resume en lenguaje simple y los envía cada lunes a las 9.",
      "BULLET:Seguimiento de leads: cuando un prospecto pide presupuesto, el agente envía la propuesta, recuerda el seguimiento y avisa si no hubo respuesta.",
      "H2: Qué necesita para funcionar bien",
      "Un agente es tan bueno como la información a la que accede. Antes de construir uno, hay que definir:",
      "BULLET:Qué herramientas puede tocar y cuáles no (reglas de permisos claras).",
      "BULLET:Qué decisiones puede tomar solo y cuáles requieren aprobación humana.",
      "BULLET:Cómo se registra cada acción, para que nada pase desapercibido.",
      "BULLET:Un protocolo de escalada: cuándo el agente se detiene y pasa el problema a una persona.",
      "H2: El costo real",
      "Contrario a lo que se piensa, un agente de IA bien acotado puede costar menos que una hora diaria de trabajo manual. La inversión no está en el modelo de IA, sino en conectarlo bien con tus sistemas y definir las reglas. Por eso los proyectos se cotizan según el alcance, no por 'el precio de la IA'.",
      "H2: Por dónde empezar",
      "El punto de partida es elegir una sola tarea repetitiva que hoy te robe horas, no tres. Con una tarea bien resuelta, el resto se encadena solo. Si no sabés por dónde cortar, una auditoría gratuita de tus procesos sirve para detectar la primera automatización que valga la pena.",
    ],
  },
  {
    slug: "5-tareas-para-automatizar",
    titulo: "5 tareas para automatizar hoy (y cuántas horas te devuelven)",
    descripcion: "La automatización no es para empresas grandes. Estas cinco tareas — con horas devueltas reales — son las que más repetimos en PyMEs.",
    fecha: "2026-09-09",
    tags: ["Automatización", "Productividad", "n8n", "Workflows"],
    meta_title: "5 tareas para automatizar hoy y cuántas horas te devuelven | PixelArch",
    meta_description: "Cinco automatizaciones concretas para PyMEs con estimaciones de horas devueltas: WhatsApp, facturación, reportes, calendario y respaldo de datos.",
    contenido: [
      "La idea de 'automatizar la empresa' suena a proyecto de tres meses y cinco cifras. La realidad es distinta: la mayoría de los beneficios vienen de automatizar tareas pequeñas y repetitivas que hoy se hacen a mano. Estas cinco son las que más repetimos en clientes chicos, con la cantidad de horas que devuelven por semana.",
      "H2: 1. Respuesta a consultas frecuentes por WhatsApp y email",
      "La misma pregunta ('¿hacen envíos?', '¿cuál es el horario?', '¿cómo pago?') llega todos los días. Un asistente automático responde al instante y deriva a una persona solo las consultas que no sabe resolver.",
      "BULLET:Horas devueltas: 3 a 5 por semana por cada canal.",
      "BULLET:Bonus: las respuestas llegan a cualquier hora, incluida la madrugada.",
      "H2: 2. Reconocimiento de pagos y avisos",
      "Cuando un cliente paga, el aviso suele llegar al correo del dueño y morir ahí. Una automatización detecta el pago, lo registra, envía el comprobante al cliente y avisa al equipo que ya puede despachar.",
      "BULLET:Horas devueltas: 2 a 3 por semana, y menos errores de facturación.",
      "BULLET:Bonus: nadie vuelve a decir 'el pago no me llegó'.",
      "H2: 3. El reporte semanal de ventas",
      "En vez de juntar números de tres plataformas cada lunes, un flujo automático arma el resumen: vendido, cobrado, pendiente, clientes nuevos. Llega por email o Slack a la hora que elijas.",
      "BULLET:Horas devueltas: 1 a 2 por semana, todos los lunes a las 9.",
      "H2: 4. Coordinación de turnos y reuniones",
      "Para quienes venden por turnos (consultas, servicios, soporte), un bot de agendamiento propone horarios, confirma la cita y envía recordatorios automáticos. Las ausencias se reducen a la mitad cuando el recordatorio existe.",
      "BULLET:Horas devueltas: 2 a 4 por semana en coordinación.",
      "H2: 5. Respaldo y alertas de datos",
      "Una copia de seguridad automática y una alerta cuando algo falla no te devuelven horas: te evitan perder un mes de trabajo en un día. Es la automatización más barata y la que más clientes arrancan después de una tragedia.",
      "BULLET:Horas devueltas: indefinidas — es un seguro, no una tarea.",
      "H2: La regla de oro",
      "Automatizar no es eliminar personas: es eliminar tareas que nadie disfruta. El equipo gana tiempo para lo que sí genera ventas: atender mejor, proponer más y cerrar negocios.",
      "Si querés saber cuál de estas cinco se adapta a tu caso, el primer paso es un mapeo corto de tus tareas repetitivas — lo hacemos sin cargo en una auditoría exprés.",
    ],
  },
  {
    slug: "hosting-compartido-vs-gestionado",
    titulo: "Hosting compartido vs gestionado: por qué tu web se cae",
    descripcion: "Tu web no se cae por casualidad: casi siempre es el hosting. Comparamos compartido, VPS y gestionado para que elijas con datos.",
    fecha: "2026-09-09",
    tags: ["Hosting", "Infraestructura", "Rendimiento", "Seguridad"],
    meta_title: "Hosting compartido vs gestionado: por qué tu web se cae | PixelArch",
    meta_description: "Compartido, VPS o gestionado: qué diferencia hay, por qué se caen las webs y qué buscar al elegir hosting para tu negocio.",
    contenido: [
      "La web se cayó a las 3 de la tarde, justo cuando llegaban los pedidos. El dueño del negocio mira la pantalla y la primera sospecha es 'se cayó el sitio'. Casi nunca es así: lo que se cayó fue el servidor donde ese sitio vive. Y la razón, en la mayoría de los casos, está en el tipo de hosting contratado.",
      "H2: Los tres niveles de hosting",
      "BULLET:Compartido: tu web comparte un servidor con cientos de otras webs. Es barato y suficiente para sitios de prueba, pero el rendimiento depende de lo que hagan tus 'vecinos'. Si uno recibe un pico de tráfico o es atacado, tu web se ralentiza o cae con él.",
      "BULLET:VPS (servidor privado virtual): tu parte del servidor está aislada. El rendimiento es predecible y podés instalar lo que quieras. El costo: la administración es tuya — actualizaciones, seguridad, backups.",
      "BULLET:Gestionado (managed): un VPS o servidor dedicado donde un equipo se encarga de todo lo aburrido: actualizaciones, monitoreo, backups, renovación de SSL, respuesta ante caídas.",
      "H2: Por qué se cae una web (en orden de frecuencia)",
      "BULLET:El 'vecino ruidoso' en hosting compartido: un pico de tráfico o un ataque a otra web del mismo servidor.",
      "BULLET:SSL vencido: la web sigue funcionando, pero el navegador la muestra como insegura y el tráfico se derrumba.",
      "BULLET:Sin monitoreo: nadie se entera de la caída hasta que llega el primer reclamo, a veces horas después.",
      "BULLET:Sin backups: la caída no es el problema; el problema es no poder volver a un punto anterior.",
      "BULLET:Actualizaciones desatendidas: el software viejo es la puerta de entrada de los ataques automatizados.",
      "H2: Lo que nadie te cuenta del hosting barato",
      "El hosting compartido 'ilimitado' publicita espacio y ancho de banda, pero la variable que importa — la capacidad de procesamiento — es la que se reparte entre todos. Cuando tu web crece, el plan que parecía gratis te cobra en lentitud lo que no te cobró en dinero.",
      "El momento de migrar no es cuando la web se cae: es cuando el tráfico legítimo empieza a crecer. Migrar con calma toma una tarde; migrar en emergencia toma una tarde y un cliente perdido.",
      "H2: Qué busca un dueño de negocio que no quiere saber de servidores",
      "Un plan gestionado tiene sentido cuando el tiempo vale más que la diferencia de precio. Lo que recibís a cambio:",
      "BULLET:Monitoreo activo 24/7 con alertas antes de que el cliente se queje.",
      "BULLET:SSL renovado automáticamente, sin vencimientos sorpresa.",
      "BULLET:Backups automáticos con restauración comprobada.",
      "BULLET:Actualizaciones de seguridad aplicadas sin que tengas que pedirlas.",
      "BULLET:Una persona responsable cuando algo falla.",
      "H2: Nuestra recomendación práctica",
      "Para un sitio institucional sin tráfico, el compartido alcanza. Para un negocio que cobra por su web — e-commerce, reservas, consultas — el costo de una caída no justifica el ahorro. La pregunta correcta no es '¿cuánto cuesta el hosting gestionado?', sino '¿cuánto pierdo el día que la web no esté online?'.",
    ],
  },
  {
    slug: "como-cobrar-online-argentina-chile",
    titulo: "Cómo cobrar online en Argentina y Chile sin perder ventas",
    descripcion: "Cobrar en el día con un cliente argentino y otro chileno parece un laberinto. Guía práctica de pasarelas, tipos de cambio y checkouts que no frenan compradores.",
    fecha: "2026-09-09",
    tags: ["Pagos online", "E-commerce", "Argentina", "Chile"],
    meta_title: "Cómo cobrar online en Argentina y Chile sin perder ventas | PixelArch",
    meta_description: "Guía práctica para cobrar online en Argentina y Chile: tarjetas internacionales, Mercado Pago, Polar y Stripe, tipos de cambio y checkouts que convierten.",
    contenido: [
      "Cobrar online en Argentina y Chile tiene una dificultad que no existe en otros mercados: la moneda. Un cliente argentino piensa en pesos, un chileno en pesos chilenos, y el negocio necesita pagar proveedores en dólares. Si el checkout no resuelve esa traducción, el carrito se abandona justo en el último paso.",
      "H2: El problema real no es la pasarela, es el tipo de cambio",
      "Muchos negocios fijan un precio en dólares y lo convierten a mano con el valor del mes pasado. Resultado: o pierden margen cuando el dólar sube, o el precio se ve desactualizado y el cliente desconfía.",
      "La solución práctica es fijar precios en dólares y convertir automáticamente al día, con una fuente confiable por país (en Argentina, el dólar venta Banco Nación; en Chile, el dólar del Banco Central). Así el precio siempre está fresco y la conversión es transparente para el comprador.",
      "H2: Qué opciones existen para cobrar",
      "BULLET:En Argentina: Mercado Pago para pagos locales en pesos (transferencia, tarjeta, cuotas) y pasarelas internacionales para cobrar en dólares a clientes de afuera.",
      "BULLET:En Chile: Stripe funciona de forma directa y es la opción más estándar para tarjetas internacionales y suscripciones.",
      "BULLET:Para suscripciones y productos digitales en ambos países: plataformas globales como Polar permiten cobrar en dólares con facturación automática y portal de cliente, sin necesidad de constituir una empresa en cada país.",
      "BULLET:Siempre: PayPal o transferencia directa como alternativa de respaldo para casos puntuales.",
      "H2: El checkout que no frena compradores",
      "El 70% de los carritos se abandona, y la mayoría de las veces la causa es el propio checkout: pedir demasiados datos, cobrar en una moneda inesperada o no mostrar el total final antes de pagar. Las reglas que aplicamos en cada integración de pagos:",
      "BULLET:Mostrar el precio final y la moneda antes de pedir la tarjeta.",
      "BULLET:Mostrar el equivalente local cuando el cobro es en dólares ('≈ $38.500 ARS'), para que nadie se sorprenda.",
      "BULLET:Permitir pagar sin crear cuenta: la cuenta se puede ofrecer después, nunca antes.",
      "BULLET:Enviar el comprobante automáticamente y con el detalle de lo comprado.",
      "H2: Y si vendés servicios mensuales",
      "Las suscripciones agregan dos capas de complejidad: el cobro recurrente y la cancelación. Un buen sistema de pagos recurrente te da:",
      "BULLET:Cobros automáticos sin que tengas que acordarte.",
      "BULLET:Un portal donde el cliente ve sus pagos y gestiona su plan.",
      "BULLET:Reintentos inteligentes cuando una tarjeta falla (ahí se recuperan muchas ventas).",
      "BULLET:Comprobantes y recibos enviados solos, cada mes.",
      "H2: Cómo empezar sin morir en el intento",
      "Arrancá simple: una pasarela, precios en dólares con conversión automática y el checkout más corto posible. Cuando el volumen lo justifique, agregás suscripciones y facturación automática. Si ya tenés algo funcionando pero perdés ventas en el último paso, una auditoría de tu checkout actual suele revelar la causa en la primera revisión.",
    ],
  },
  {
    slug: "monitoreo-24-7",
    titulo: "¿Tu web está caída y no te enterás? Monitoreo 24/7",
    descripcion: "Una caída sin monitoreo no se detecta: se descubre. Cuánto cuesta, por qué no te enterás y qué vigila un servicio de monitoreo serio.",
    fecha: "2026-09-09",
    tags: ["Monitoreo", "Uptime", "Mantenimiento", "Soporte"],
    meta_title: "Monitoreo 24/7: tu web caída y no te enterás | PixelArch",
    meta_description: "Cuánto cuesta una caída sin detectar, por qué el monitoreo pasivo no alcanza y qué vigila un servicio de mantenimiento serio en tu web.",
    contenido: [
      "Hay dos tipos de caídas de web: las que nadie nota y las que nadie descubre. Las primeras duran minutos y se resuelven solas. Las segundas duran horas — a veces días — y se descubren cuando un cliente escribe para preguntar '¿qué pasó con mi pedido?'. La diferencia entre una y otra se llama monitoreo.",
      "H2: El costo real de una caída",
      "Una hora sin web no se mide solo en ventas perdidas. Se mide en:",
      "BULLET:Ventas directas que no se procesaron (el costo obvio).",
      "BULLET:SEO: si la caída se repite, Google pierde confianza y el posicionamiento baja durante semanas.",
      "BULLET:Confianza: cada visitante que encontró la web caída y no volvió es un cliente que no vas a recuperar.",
      "BULLET:Horas de reclamos: el soporte responde 'estamos revisando' mientras el problema lleva horas resuelto en silencio.",
      "H2: Por qué no te enterás",
      "El problema de no tener monitoreo no es la caída en sí: es que nadie la detecta hasta que alguien la padece. El servidor no te llama para avisarte. El 'revisemos de vez en cuando' de un amigo técnico no funciona porque la mayoría de las caídas ocurren de noche o los fines de semana — justo cuando nadie revisa.",
      "H2: Qué vigila un monitoreo serio",
      "Un servicio de monitoreo completo no se limita a 'ping, está vivo'. Vigila:",
      "BULLET:Disponibilidad: que la web responda desde distintos puntos del mundo, no solo desde tu oficina.",
      "BULLET:SSL: que el certificado esté vigente, con alerta antes de que expire (la caída más silenciosa de todas).",
      "BULLET:Tiempo de respuesta: que cargue rápido, no solo que cargue. Una web que tarda 8 segundos está 'online' y es igual de inútil.",
      "BULLET:Backups: que las copias se generen y que se puedan restaurar — un backup que nunca se probó no es un backup.",
      "BULLET:Logs y errores: los errores de servidor que se acumulan sin que nadie los vea.",
      "H2: Qué pasa cuando algo falla (la parte que importa)",
      "El monitoreo detecta; el servicio se completa cuando alguien arregla. Un plan de mantenimiento real tiene dos fases: la alerta automática (correo, WhatsApp, Slack) y la respuesta humana — la persona que ya conoce tu infraestructura y actúa sobre el problema, no un ticket que espera turno.",
      "H2: La regla práctica",
      "Si tu web es tu principal canal de venta o de consultas, el monitoreo no es un extra: es parte del costo de tener el negocio online. La pregunta no es '¿cuánto cuesta monitorearla?' sino '¿cuánto me costó la última caída que nadie detectó?'.",
    ],
  },
{
    slug: "como-elegir-el-disco-de-tu-notebook",
    titulo: "Cómo elegir el disco de tu notebook: HDD, SSD SATA, M.2 NVMe y lo nuevo del mercado",
    descripcion: "HDD, SSD SATA, M.2 NVMe, PCIe 5.0, eMMC... La gente se confunde porque hay demasiadas siglas. Esta guía las explica en orden y te dice cuál elegir según tu caso.",
    fecha: "2026-09-09",
    tags: ["SSD", "HDD", "M.2", "NVMe", "Notebooks"],
    meta_title: "Cómo elegir el disco de tu notebook: HDD vs SSD vs M.2 | PixelArch",
    meta_description: "Guía práctica para elegir el almacenamiento de tu notebook: HDD, SSD SATA, M.2 NVMe, PCIe 4.0/5.0, QLC y eMMC, explicados sin tecnicismos y con recomendaciones por caso.",
    contenido: [
      "Si estás buscando disco para tu notebook y sentís que leíste diez artículos y te confundiste más, no es tu culpa: el mercado mezcla formato físico (HDD, SSD 2.5\", M.2), protocolo de conexión (SATA, NVMe), generación del bus (PCIe 3.0, 4.0, 5.0) y tecnología de memoria (TLC, QLC) en la misma frase. Esta guía separa cada concepto y te dice cuál elegir según tu caso.",
      "H2: El HDD: el disco mecánico que todavía vive",
      "El disco duro clásico tiene platos giratorios y una aguja que lee los datos. Es la tecnología más vieja y la única que sigue siendo mecánica. Sus números hoy:",
      "BULLET:Velocidad: hasta 160 MB/s en condiciones ideales, mucho menos con archivos pequeños.",
      "BULLET:Precio: el costo por gigabyte más bajo de todos.",
      "BULLET:Ventajas: capacidad enorme por poca plata (2 TB por el precio de un SSD chico) y resistencia a ciclos de escritura casi ilimitada.",
      "BULLET:Desventajas: lento, frágil (no lo golpees), ruidoso, y hace que Windows o macOS tarden minutos en arrancar.",
      "Hoy un HDD tiene sentido para archivo muerto (fotos, backups, medios) o en equipos de escritorio con un SSD como disco principal. En una notebook, como único disco, no.",
      "H2: El SSD SATA: el salto que más se nota por poca plata",
      "Un SSD SATA 2.5\" reemplaza al HDD en el mismo lugar físico y con el mismo cable, pero sin partes móviles: los datos viven en chips de memoria flash. El límite lo pone el protocolo SATA III: unos 550 MB/s.",
      "BULLET:Por qué importa: pasar de HDD a SSD SATA es el upgrade más notorio que existe en una notebook vieja. El arranque pasa de 90 segundos a 15.",
      "BULLET:Cuidado al comprar: los modelos 'DRAM-less' (sin caché dedicada) son baratos pero se vuelven lentos con escrituras pesadas o cuando se llenan. Un SSD con caché cuesta poco más y dura mejor.",
      "BULLET:Para quién: notebooks de 8 a 12 años con slot SATA, o presupuestos muy ajustados.",
      "H2: M.2: formato, no velocidad",
      "El error más común: creer que M.2 significa rápido. M.2 es solo el formato físico — una tira delgada que se atornilla a la placa. Dentro de ese formato existen dos mundos:",
      "BULLET:M.2 SATA: mismo protocolo que el SSD 2.5\" (~550 MB/s), solo que en formato tira. Sirve en notebooks donde el slot M.2 no soporta NVMe.",
      "BULLET:M.2 NVMe: usa el bus PCIe directamente. Ahí sí hablamos de velocidad en serio: 3.500 MB/s en PCIe 3.0, unos 7.000 MB/s en PCIe 4.0 y más de 10.000 MB/s en PCIe 5.0.",
      "Antes de comprar un M.2, buscá si tu notebook soporta NVMe (suele estar en la ficha técnica del fabricante como 'M.2 PCIe'). Comprar NVMe para un slot que solo lee SATA no sirve — y al revés tampoco.",
      "H2: Lo nuevo que conviene conocer",
      "BULLET:PCIe 4.0 y 5.0: la velocidad real del M.2 NVMe depende de la generación que soporte tu notebook. Un disco PCIe 5.0 en un slot 4.0 funciona, pero a la velocidad del 4.0.",
      "BULLET:QLC vs TLC: la memoria flash. TLC es más duradera y estable; QLC es más barata y pierde rendimiento cuando el disco está casi lleno. Para el día a día, TLC.",
      "BULLET:eMMC: el almacenamiento soldado de las notebooks más baratas. Es básicamente una memoria tipo pendrive integrada. Alcanza para navegar, pero se llena rápido y no se puede reemplazar. Si el presupuesto da, evitalo.",
      "BULLET:Disco soldado: muchas notebooks modernas traen el SSD soldado a la placa, sin slot de expansión. Antes de comprar, fijate si tiene slot libre para agregar almacenamiento.",
      "H2: Cuál elegir según tu caso",
      "BULLET:Notebook vieja con HDD y poco presupuesto: SSD SATA 2.5\" con caché. El cambio más barato y más notorio que existe.",
      "BULLET:Notebook moderna con slot M.2: M.2 NVMe PCIe 3.0 o 4.0 (la generación que soporte tu equipo). Es el estándar actual.",
      "BULLET:Mucho almacenamiento secundario: un HDD 2.5\" o 3.5\" externo para backups y archivos que no usás todos los días.",
      "BULLET:Notebook económica nueva: si trae eMMC, considerá sumar un SSD por el slot M.2 o cambiar de modelo.",
      "H2: La regla de oro",
      "El disco no se elige por la marca ni por la sigla más nueva: se elige por la velocidad que tu notebook puede aprovechar y por el uso que le vas a dar. Un NVMe PCIe 5.0 no le cambia la vida a una notebook que trabaja con documentos; un SSD SATA se la cambia a una que hoy arranca con un HDD.",
      "Si tenés dudas con tu equipo puntual (qué slot tiene, si soporta NVMe, qué generación PCIe), mandanos el modelo y te decimos exactamente qué disco comprar — sin vueltas y sin venderte el más caro.",
    ],
  },
  {
    slug: "cuanto-cuesta-una-pagina-web-argentina",
    titulo: "¿Cuánto cuesta una página web en Argentina? (Guía 2026 con rangos reales)",
    descripcion: "La pregunta que todos hacen y nadie responde con números. Acá van los rangos reales de 2026, qué hace subir el precio y cómo leer un presupuesto sin sorpresas.",
    fecha: "2026-09-12",
    tags: ["Precios", "Diseño web", "Argentina", "Pymes"],
    meta_title: "¿Cuánto cuesta una página web en Argentina? Rangos 2026 | PixelArch",
    meta_description: "Rangos reales de precios de páginas web en Argentina (2026): landing, sitio institucional, e-commerce y desarrollo a medida. Qué incluye cada presupuesto.",
    contenido: [
      "Es la primera pregunta que hace todo cliente y la última que responden las agencias. '¿Cuánto sale una página web?' no tiene una respuesta única porque una página web no es una cosa: es un proyecto, y como todo proyecto, su precio depende del alcance. Lo que sí se puede dar son rangos reales — y eso es lo que hacemos acá.",
      "H2: Por qué nadie te da un precio de una",
      "Cuando alguien te responde 'depende' no está esquivando la pregunta: está siendo honesto. Una landing de una sección y un e-commerce con 500 productos y facturación automática son ambos 'páginas web', y sus costos no se parecen en nada. La diferencia está en el trabajo: diseño, contenidos, integraciones, pruebas y el soporte que viene después.",
      "La forma seria de cotizar es en dos pasos: primero entender el alcance (qué tiene que hacer la web), después poner el precio. Cualquiera que te dé un número firme sin hacer la primera pregunta te está vendiendo un template, no una solución.",
      "H2: Los rangos que se manejan hoy (2026)",
      "Los siguientes rangos son en dólares y cubren el mercado profesional argentino — ni el template de $20.000 ni la agencia corporativa de US$20.000. Sirven como orden de magnitud para comparar presupuestos.",
      "BULLET:Landing page (una sola página, un objetivo): desde US$500 a US$1.200. Ideal para campañas, validar un producto o un servicio puntual.",
      "BULLET:Sitio institucional (5 a 10 secciones: home, servicios, nosotros, contacto): desde US$1.000 a US$3.000, según contenidos e integraciones.",
      "BULLET:E-commerce (catálogo, carrito, pagos, envíos): desde US$2.500 a US$8.000, muy dependiente de la cantidad de productos y la logística.",
      "BULLET:Desarrollo a medida (sistemas, reservas, paneles, integraciones con tus herramientas): desde US$3.000 en adelante, cotizado por alcance y por etapas.",
      "H2: Qué hace subir el precio",
      "Dentro de un mismo tipo de proyecto, estas variables son las que mueven el número:",
      "BULLET:Cantidad de integraciones: cada sistema externo (pagos, facturación, CRM, stock, WhatsApp) suma desarrollo y pruebas.",
      "BULLET:Contenidos: si los textos, fotos y videos los tiene que producir alguien, eso es trabajo — y se nota en el presupuesto.",
      "BULLET:Diseño a medida vs template adaptado: un diseño propio cuesta más horas, pero también diferencia a tu negocio de los miles que usan la misma plantilla.",
      "BULLET:Idiomas: cada idioma adicional multiplica contenido, revisión y ajustes de SEO.",
      "BULLET:Automatizaciones: formularios que disparan acciones, turnos que se confirman solos, reportes automáticos. Cada flujo suma.",
      "H2: Qué debería incluir SIEMPRE un presupuesto serio",
      "Si tu presupuesto no menciona estos puntos, preguntá explícitamente — es donde aparecen las sorpresas:",
      "BULLET:Dominio y hosting del primer año (o al menos quién lo contrata y cuánto cuesta).",
      "BULLET:Certificado SSL (el candado de seguridad) configurado y renovándose solo.",
      "BULLET:Diseño responsive: que se vea y funcione bien en celular, que es donde llega la mayoría del tráfico.",
      "BULLET:SEO técnico base: títulos, descripciones, velocidad, sitemap. Sin esto, Google no te encuentra.",
      "BULLET:Analítica configurada, para saber qué pasa después del lanzamiento.",
      "BULLET:Qué incluye el soporte post-lanzamiento y qué se cobra aparte.",
      "H2: El precio barato sale caro",
      "La web de $50.000 con 'todo incluido' existe y funciona: hasta que necesitás cambiar algo. Los problemas típicos del presupuesto más bajo:",
      "BULLET:Template genérico que se ve igual al de otros cien negocios.",
      "BULLET:SEO inexistente: la web existe pero nadie la encuentra.",
      "BULLET:Hosting compartido barato que se cae justo cuando llega el tráfico.",
      "BULLET:Cero soporte: el que la hizo no está más y nadie sabe cómo tocar nada.",
      "BULLET:Sin respaldo: un error de configuración y se pierde todo.",
      "H2: Cómo pedir presupuesto (y comparar manzanas con manzanas)",
      "Para comparar presupuestos de verdad, pedí siempre lo mismo: alcance detallado, qué incluye y qué no, plazos por etapa, forma de pago (mejor por hitos: anticipo, avances, entrega) y qué pasa después del lanzamiento. Con esos cinco puntos, los números se vuelven comparables.",
      "En PixelArch cotizamos así: cada proyecto se arma con hitos claros, se paga a medida que avanza y el detalle queda por escrito antes de empezar. Si querés un número real para tu caso, contanos qué necesitás y te armamos el presupuesto por etapas.",
    ],
  },
  {
    slug: "whatsapp-business-automatizar-trato-humano",
    titulo: "WhatsApp Business: cómo automatizar sin perder el trato humano",
    descripcion: "Automatizar WhatsApp no es poner un robot que responde cualquier cosa. Qué automatizar, qué no, y cómo hacer que el traspaso a una persona sea invisible.",
    fecha: "2026-09-15",
    tags: ["WhatsApp", "Automatización", "Atención al cliente", "Ventas"],
    meta_title: "WhatsApp Business: automatizar sin perder el trato humano | PixelArch",
    meta_description: "Qué automatizar en WhatsApp Business y qué no, cómo hacer el traspaso a un humano invisible y cómo medir si la automatización mejora tus ventas.",
    contenido: [
      "En Argentina y Chile, WhatsApp no es un canal más: es el canal principal. El cliente pregunta por ahí, negocia por ahí y compra por ahí. El problema es que detrás de ese canal hay una persona — vos — que no puede responder a las 11 de la noche ni mientras atiende a otro cliente.",
      "La tentación es automatizar todo con un bot. El resultado suele ser el opuesto: respuestas rígidas, clientes frustrados y ventas perdidas. La clave no es automatizar todo, sino automatizar lo correcto y hacer invisible el traspaso a un humano.",
      "H2: Por qué el tiempo de respuesta lo es todo",
      "En ventas por WhatsApp, la velocidad pesa más que el precio. Un cliente que pregunta por un producto y recibe respuesta en minutos compra mucho más que uno que espera horas. Y el que espera, no solo no compra: se va a preguntarle a otro. Responder rápido es la ventaja competitiva más barata que existe — pero es imposible hacerlo a mano, todos los días, a toda hora.",
      "H2: Qué automatizar (sin que se note)",
      "BULLET:Saludo y preguntas frecuentes: horarios, formas de pago, zonas de envío, precios de lista. La mayoría de los mensajes entrantes son estas preguntas.",
      "BULLET:Fuera de horario: responder al instante 'te leemos mañana a las 9' con la info básica resuelta — no es lo mismo que dejar el mensaje en visto.",
      "BULLET:Turnos y reservas: confirmar disponibilidad, agendar y recordar la cita automáticamente.",
      "BULLET:Seguimiento: recordar al cliente que quedó en decidir, avisar cuando el pedido salió, pedir la reseña después de la compra.",
      "BULLET:Derivación ordenada: si la consulta necesita a una persona, que llegue con contexto ('cliente quiere cambiar talla del pedido #123').",
      "H2: Qué NO automatizar nunca",
      "BULLET:La negociación: los precios y condiciones se conversan con una persona. Un bot que negocia quema margen o espanta clientes.",
      "BULLET:Los reclamos delicados: un problema con un pedido o un cobro necesita empatía, no menú de opciones.",
      "BULLET:El cierre de ventas importantes: cuando el cliente está listo para comprar, quiere hablar con alguien que le confirme y lo acompañe.",
      "BULLET:Las disculpas: si algo salió mal, un mensaje automático ofende más de lo que calma.",
      "H2: La regla del traspaso invisible",
      "La automatización bien hecha tiene una sola regla: el cliente nunca debería notar el cambio. Si el flujo automático resuelve, perfecto. Si no, tiene que derivar a una persona en segundos, con todo el contexto de la conversación y sin pedirle al cliente que repita lo que ya dijo. 'Te paso con alguien del equipo' es aceptable; 'elegí una opción del menú' después de tres respuestas equivocadas, no.",
      "H2: WhatsApp Business App vs API",
      "La app de WhatsApp Business (gratis) alcanza para respuestas rápidas guardadas y mensajes de ausencia — útil si sos vos y nadie más. Cuando el volumen crece, el equipo es más de uno o querés automatizaciones de verdad, aparece la API de WhatsApp Business: permite varios agentes en el mismo número, integración con tu sistema y flujos automáticos completos.",
      "H2: Cómo saber si está funcionando",
      "Automatizar sin medir es apostar. Las métricas que importan: tiempo de primera respuesta (debería bajar a segundos), conversaciones resueltas sin humano, consultas que terminan en venta y, sobre todo, cuántos clientes piden 'hablar con una persona' apenas empieza la conversación. Si ese número es alto, la automatización está estorbando en vez de ayudar.",
      "El mejor punto de partida no es automatizar todo el WhatsApp: es elegir las tres preguntas que más te repiten y resolverlas bien, con traspaso humano a un toque de distancia. Si querés saber cuáles de tus consultas son automatizables, una auditoría de tus conversaciones lo muestra en una tarde.",
    ],
  },
  {
    slug: "integrar-mercado-pago-en-tu-web",
    titulo: "Cómo integrar Mercado Pago en tu web (sin dolores de cabeza)",
    descripcion: "Link de pago, checkout integrado o suscripciones: las tres formas de cobrar con Mercado Pago, cuándo conviene cada una y el error que casi todos cometen.",
    fecha: "2026-09-18",
    tags: ["Mercado Pago", "Pagos online", "E-commerce", "Integraciones"],
    meta_title: "Cómo integrar Mercado Pago en tu web: guía práctica | PixelArch",
    meta_description: "Guía práctica de Mercado Pago para tu web: link de pago, checkout integrado y suscripciones, webhooks y los errores más comunes al cobrar online.",
    contenido: [
      "Mercado Pago es la forma estándar de cobrar online en Argentina: la usa casi todo el mundo y el comprador ya le tiene confianza. La pregunta no es si integrarla, sino cuál de sus tres formas usar. Cada una tiene un costo, una experiencia distinta para el cliente y un nivel de trabajo distinto para vos.",
      "H2: Las tres formas de cobrar con Mercado Pago",
      "BULLET:Link de pago: generás un link por el monto a cobrar y se lo mandás al cliente por WhatsApp o email. Cero desarrollo, funciona desde el primer día.",
      "BULLET:Checkout integrado (Checkout Pro): el botón de pago vive en tu web, pero el cliente paga en el entorno de Mercado Pago. El equilibrio entre trabajo e integración.",
      "BULLET:Suscripciones (preapproval): cobros recurrentes automáticos, para membresías o servicios mensuales. Es la más compleja de las tres.",
      "H2: Link de pago: la opción más rápida (y la más subestimada)",
      "Para muchos negocios de servicios, el link de pago es todo lo que necesitan: cotizás por WhatsApp, acordás el monto y mandás el link. El cliente paga con tarjeta, transferencia o cuotas, y la plata llega igual. Sus límites: cada cobro requiere generar un link, no se integra con el stock de tu web y la experiencia es más 'a mano' — pero para servicios profesionales, proyectos por etapas y cobros puntuales, es imbatible en relación costo-beneficio.",
      "H2: Checkout integrado: cuándo vale la pena",
      "Cuando tu web vende sola — un carrito, un catálogo, precios públicos — el checkout integrado es el paso natural: el cliente arma el carrito, aprieta 'pagar' y termina en Mercado Pago sin fricción. El desarrollo es mayor, pero la conversión también: cada paso manual que elimines se traduce en ventas.",
      "H2: El webhook: la parte que casi todos olvidan",
      "Integrar Mercado Pago no termina cuando el cliente paga: empieza ahí. El error más común es confirmar la venta 'cuando el cliente vuelve a la web' — que es exactamente lo que no pasa cuando alguien paga con transferencia o cierra la pestaña. La forma correcta es el webhook: Mercado Pago le avisa a tu servidor que el pago se acreditó, tu sistema lo registra, marca el pedido como pagado y dispara lo que corresponda (email, envío, factura).",
      "BULLET:Sin webhook: pedidos 'pagos' que nunca se acreditaron y clientes enojados.",
      "BULLET:Con webhook: confirmación automática, en segundos, aunque el cliente nunca vuelva a la web.",
      "BULLET:Clave: el webhook tiene que ser idempotente (si llega dos veces el mismo aviso, no duplicar el pago) y verificar la firma para que nadie lo falsifique.",
      "H2: Los errores que vemos una y otra vez",
      "BULLET:Confiar en el retorno del navegador en vez del webhook.",
      "BULLET:No guardar el identificador de la operación (después no hay forma de auditar nada).",
      "BULLET:No probar con pagos reales chicos antes de salir a producción.",
      "BULLET:Ignorar los estados intermedios: un pago puede estar pendiente, rechazado o en revisión — no todo es 'aprobado' o 'fallido'.",
      "H2: Cuánto cuesta integrar Mercado Pago",
      "La comisión de Mercado Pago la define la plataforma según el medio de pago y el plazo de acreditación (está publicada en su sitio y cambia con el tiempo). El costo de desarrollo depende de la forma elegida: un link de pago puede ser cero (se genera a mano o desde un panel simple); un checkout integrado con webhook es desarrollo de unas horas; las suscripciones automáticas son el proyecto más grande.",
      "En PixelArch integramos las tres formas: desde paneles internos que generan links de pago con un clic hasta checkouts completos con confirmación automática. Si tu web ya vende pero perdés ventas en el pago, una auditoría del flujo actual muestra exactamente dónde está la fuga.",
    ],
  },
  {
    slug: "seo-local-google-maps",
    titulo: "SEO local: cómo aparecer en Google Maps cuando te buscan",
    descripcion: "Casi la mitad de las búsquedas tienen intención local. Si tu negocio no aparece en el mapa, esas búsquedas se las queda otro. Guía práctica de SEO local.",
    fecha: "2026-09-21",
    tags: ["SEO", "Google Maps", "Marketing local", "Negocios"],
    meta_title: "SEO local: cómo aparecer en Google Maps | PixelArch",
    meta_description: "Guía práctica de SEO local: ficha de Google Business Profile, reseñas, NAP consistente y la web que acompaña para aparecer en Google Maps.",
    contenido: [
      "Cuando alguien busca 'veterinaria cerca de mí' o 'plomero en Palermo', no está buscando una web: está buscando una decisión. Google le muestra tres negocios en el mapa y, en la mayoría de los casos, ahí termina la búsqueda. Si tu negocio no está entre esos tres, el cliente no te descartó: nunca te vio.",
      "H2: Google Business Profile: la ficha gratuita que casi nadie completa",
      "La ficha de Google (ex Google My Business) es el activo de SEO local más importante y es gratis. Completarla bien es la diferencia entre aparecer y no existir:",
      "BULLET:Categoría principal exacta: 'veterinaria' posiciona distinto que 'tienda de mascotas'. Elegí la que describe tu servicio principal, no la más amplia.",
      "BULLET:Horarios reales (y feriados): un negocio 'abierto' que está cerrado recibe una reseña de una estrella que pesa más que veinte buenas.",
      "BULLET:Fotos propias y actualizadas: fachada, interior, equipo, trabajos. Los perfiles con fotos reciben muchas más consultas.",
      "BULLET:Servicios y productos cargados uno por uno, con descripción. Es texto que Google usa para entender qué ofrecés.",
      "BULLET:Preguntas y respuestas: cargá vos las preguntas frecuentes y respondelas. Es contenido gratis en tu perfil.",
      "H2: Reseñas: el factor que más mueve la aguja",
      "Para el ranking local, las reseñas pesan más que casi cualquier otra cosa. Las reglas:",
      "BULLET:Pedilas siempre, en el momento de la verdad (cuando el cliente acaba de recibir el servicio).",
      "BULLET:Facilitá el camino: un link directo a 'dejar reseña', por WhatsApp, en el momento justo.",
      "BULLET:Respondé todas — las buenas con agradecimiento sincero, las malas con calma y solución. La respuesta no es para el que se quejó: es para los cien que van a leer.",
      "BULLET:Nunca las compres. Google las detecta, las borra y puede suspender tu ficha. El riesgo no vale la pena.",
      "H2: NAP consistente: aburrido pero crítico",
      "NAP es nombre, dirección y teléfono. Tienen que ser idénticos en tu ficha de Google, tu web, tus redes y cualquier directorio donde aparezcas. Una dirección con 'Av.' en un lado y 'Avenida' en otro confunde a Google y diluye tu señal local. Revisá una vez y quedate tranquilo por años.",
      "H2: La web que acompaña al mapa",
      "La ficha te pone en el mapa; la web te sostiene en los resultados. Para SEO local:",
      "BULLET:Una página por servicio y por zona ('plomería en Caballito', 'veterinaria en Belgrano') con contenido propio — no la misma página copiada con el barrio cambiado.",
      "BULLET:Datos estructurados (schema LocalBusiness) con dirección, horarios y teléfono: le dicen a Google exactamente qué sos.",
      "BULLET:Velocidad móvil: la mayoría de las búsquedas locales pasan en el celular, en la calle, con prisa.",
      "BULLET:Botón de WhatsApp y teléfono clickeable: de la búsqueda a la consulta en un toque.",
      "H2: Errores que te hunden",
      "BULLET:Inventar o exagerar la zona de cobertura: Google verifica y penaliza.",
      "BULLET:Cambiar la categoría cada mes para 'probar suerte': cada cambio resetea señales.",
      "BULLET:Ignorar la ficha por meses: los perfiles activos rankean mejor que los abandonados.",
      "BULLET:Llenar la descripción de palabras clave repetidas: se lee mal para humanos y Google lo nota.",
      "H2: Cómo medir si funciona",
      "Tu ficha tiene métricas propias: cuántas veces apareciste en búsquedas, cuántos pidieron indicaciones, cuántos llamaron y cuántos visitaron tu web desde el perfil. Esas cuatro cifras, mes a mes, te dicen si el trabajo local está rindiendo — sin depender de ningún reporte de agencia.",
      "El SEO local no es magia: es una ficha bien hecha, reseñas reales y una web que acompaña. Si querés saber cómo estás parado hoy, una auditoría de tu presencia local te muestra el punto de partida en minutos.",
    ],
  },
  {
    slug: "correo-con-tu-dominio",
    titulo: "Correo con tu dominio: por qué tu negocio no debería usar @gmail",
    descripcion: "Un correo @gmail para un negocio dice más de lo que pensás. Cuánto cuesta tener correo con tu dominio, cómo migrar y la configuración que casi todos olvidan.",
    fecha: "2026-09-24",
    tags: ["Correo", "Dominio", "Profesionalismo", "Pymes"],
    meta_title: "Correo con tu dominio: por qué no usar @gmail en tu negocio | PixelArch",
    meta_description: "Por qué tu negocio debería usar correo con dominio propio, cuánto cuesta, cómo migrar sin perder correos y la configuración SPF, DKIM y DMARC explicada simple.",
    contenido: [
      "Imaginate que estás por contratar un servicio y recibís el presupuesto desde 'serviciospymero@gmail.com'. No hace falta que nadie te explique qué sentís: algo no cierra. Ese mismo correo, con un dominio propio, cuenta otra historia — y la diferencia cuesta menos que un almuerzo por mes.",
      "H2: Lo que un @gmail dice de tu negocio",
      "El correo es la carta de presentación digital más repetida de tu negocio: va en el presupuesto, en la factura, en el CV, en la web. Un @gmail transmite 'emprendimiento informal'; un correo con tu dominio transmite 'empresa'. No es snobismo: es la misma señal que un local con cartel versus un local sin nombre. Además hay un efecto práctico: los correos desde dominios propios bien configurados tienen mejor entregabilidad (menos probabilidad de caer en spam) que los masivos desde cuentas gratuitas.",
      "H2: Las opciones para tener correo con tu dominio",
      "BULLET:Google Workspace: la opción más completa (Gmail con tu dominio, Drive, Meet). De las más caras por usuario, pero la más conocida.",
      "BULLET:Zoho Mail: la relación precio-calidad del mercado. Tiene plan gratuito para uso básico y planes pagos muy económicos.",
      "BULLET:Microsoft 365: la opción natural si tu equipo ya vive en Word y Excel.",
      "BULLET:Correo del proveedor de hosting: suele venir incluido en planes de hosting y sirve para arrancar, aunque la interfaz y el soporte son más básicos.",
      "H2: Lo que casi nadie configura (y debería)",
      "Tener el correo andando no alcanza: hay que decirle al mundo que tus correos son legítimos. Tres registros DNS hacen el trabajo:",
      "BULLET:SPF: lista de servidores autorizados a enviar correo en nombre de tu dominio. Sin él, cualquiera puede 'enviar como vos'.",
      "BULLET:DKIM: una firma digital que certifica que el correo salió de tus servidores y no fue alterado.",
      "BULLET:DMARC: la política que le dice a los proveedores qué hacer con los correos que no pasan las verificaciones (rechazarlos o marcarlos como sospechosos).",
      "Configurados bien, tus correos llegan; configurados mal, tus propuestas a clientes terminan en spam y nunca te enterás.",
      "H2: Cuánto cuesta",
      "Los planes arrancan cerca de US$1 por usuario por mes en las opciones económicas y suben a US$6-7 en las más completas. Para un negocio de una o dos personas, hablamos de menos de US$15 al mes — mucho menos que el costo de parecer informal en cada propuesta.",
      "H2: Cómo migrar sin perder nada",
      "BULLET:Paso 1: crear las casillas nuevas en el proveedor elegido (con tu dominio, que ya tenés o comprás por unos US$10 al año).",
      "BULLET:Paso 2: configurar SPF, DKIM y DMARC desde el primer día.",
      "BULLET:Paso 3: migrar los correos históricos (la mayoría de los proveedores lo hace con un asistente).",
      "BULLET:Paso 4: reenviar el correo viejo a la casilla nueva durante un tiempo, para no perder nada de lo que llegue al @gmail.",
      "BULLET:Paso 5: actualizar el correo en la web, las redes, la facturación y los clientes frecuentes.",
      "H2: El detalle que hace la diferencia",
      "Además del correo propio, configurá el 'desde' correcto: que cuando escribas, el destinatario vea 'tu nombre — Tu Negocio', no solo una dirección. Y si vas a hacer envíos masivos (newsletters, promociones), usá un servicio especializado: mandar 500 correos desde tu casilla personal es la forma más rápida de que todos terminen en spam.",
      "Tener correo con tu dominio es de esas mejoras que no se ven, pero se notan en cada interacción. Si querés que lo dejemos funcionando con tu dominio, la configuración completa — incluyendo SPF, DKIM y DMARC — la hacemos en el día.",
    ],
  },
  {
    slug: "cuanto-cuesta-mantener-una-web",
    titulo: "¿Cuánto cuesta mantener una web por año? (y qué incluye)",
    descripcion: "El precio de la web es la mitad de la historia: la otra mitad es lo que pagás todos los años. Desglose real de costos, qué pasa si no hay mantenimiento y cómo elegir un plan.",
    fecha: "2026-09-27",
    tags: ["Mantenimiento", "Costos", "Hosting", "Soporte"],
    meta_title: "¿Cuánto cuesta mantener una web por año? Costos y planes | PixelArch",
    meta_description: "Costos reales de mantener una web por año: dominio, hosting, SSL, correo, actualizaciones y soporte. Qué incluye un plan serio y cómo elegir el tuyo.",
    contenido: [
      "Cuando alguien contrata una web, suele pensar en el costo como un pago único. Meses después llega la sorpresa: el dominio que vence, el hosting que se renueva, la actualización que rompió algo, el certificado que expiró sin aviso. El mantenimiento no es un gasto oculto: es el costo de que la web siga viva, segura y vendiendo.",
      "H2: Lo que pagás todos los años (aunque nadie lo mire)",
      "BULLET:Dominio: US$10-15 al año. Barato, pero si vence, tu web y todos tus correos se caen de un día para el otro.",
      "BULLET:Hosting: desde US$5 al mes en un plan compartido hasta US$50 o más en servidores gestionados. Acá se paga la diferencia entre 'se cae a veces' y 'está siempre arriba'.",
      "BULLET:SSL: el candado de seguridad. En la mayoría de los hostings modernos viene incluido y se renueva solo; en otros es un costo aparte.",
      "BULLET:Correo profesional: US$1-7 por usuario por mes, si lo tenés con tu dominio.",
      "BULLET:Licencias y herramientas: plugins premium, temas, constructores. Varía mucho según con qué esté hecha la web.",
      "Sumando: un sitio institucional típico cuesta entre US$150 y US$600 al año solo en infraestructura. Si tu presupuesto anual es cero, en algún lado va a fallar.",
      "H2: Los costos que aparecen cuando algo falla",
      "El mantenimiento preventivo se paga solo cuando lo comparás con la alternativa:",
      "BULLET:Sitio hackeado: limpieza, restauración y el tiempo que la web pasa caída (a veces días).",
      "BULLET:SSL vencido: los navegadores muestran 'sitio no seguro' y el tráfico se derrumba — y se recupera lento.",
      "BULLET:Web caída un fin de semana largo: si nadie monitorea, nadie la levanta hasta el lunes.",
      "BULLET:Actualización que rompió todo: sin backup reciente, no hay vuelta atrás.",
      "BULLET:Cambios urgentes sin soporte: pagar horas de emergencia a precio de urgencia es siempre más caro que un plan mensual.",
      "H2: Correctivo vs preventivo: la cuenta que nadie hace",
      "El mantenimiento correctivo es apagar incendios: pagás cuando algo se rompe, a las apuradas, con la web caída y los clientes mirando. El preventivo es lo opuesto: actualizaciones al día, backups que se prueban, monitoreo que avisa antes de que el cliente note algo, y horas incluidas para los cambios chicos. El primero parece más barato hasta que ocurre la primera emergencia.",
      "H2: Qué incluye un plan de soporte serio",
      "BULLET:Monitoreo 24/7 con alertas automáticas: si la web se cae, te enterás vos antes que tus clientes.",
      "BULLET:Backups automáticos con restauración probada: la red de seguridad que solo se valora el día que se necesita.",
      "BULLET:Actualizaciones de seguridad aplicadas y probadas, no 'a ver qué pasa'.",
      "BULLET:SSL y dominio vigilados: cero vencimientos sorpresa.",
      "BULLET:Horas mensuales para cambios y mejoras: textos, fotos, secciones nuevas.",
      "BULLET:Prioridad y respuesta humana cuando algo falla — no un ticket que espera turno.",
      "H2: Cómo decidir cuánto necesitás",
      "La regla es simple: si tu web trae clientes, el mantenimiento no es un gasto, es parte del costo de vender. Un negocio que factura todos los meses por su web no puede darse el lujo de tenerla caída una semana o de perderla por un hackeo. En cambio, una web institucional que solo existe 'por presencia' puede vivir con un plan básico de monitoreo y backups.",
      "En PixelArch los planes de soporte arrancan en US$25 al mes (básico: monitoreo, backups, actualizaciones, SSL) y US$200 al mes (premium: todo lo anterior más horas de desarrollo y prioridad). Si no sabés cuál te corresponde, contanos cómo usás tu web y te decimos qué plan tiene sentido — sin venderte el más caro.",
    ],
  },
]

function blocks(items: string[]) {
  return items.map((raw) => {
    if (raw.startsWith("H2:")) {
      return {
        _type: "block",
        style: "h2",
        children: [{ _type: "span", text: raw.slice(3) }],
      }
    }
    if (raw.startsWith("BULLET:")) {
      return {
        _type: "block",
        style: "normal",
        listItem: "bullet",
        level: 1,
        children: [{ _type: "span", text: raw.slice(7) }],
      }
    }
    return {
      _type: "block",
      style: "normal",
      children: [{ _type: "span", text: raw }],
    }
  })
}

async function run() {
  console.log("Conectando a Sanity...\n")

  for (const a of ARTICULOS) {
    const existing = await client.fetch(`*[_type == "articulo" && slug.current == $slug][0]{_id}`, { slug: a.slug })
    if (existing) {
      console.log(`SKIP  ${a.slug} (ya existe)`)
      continue
    }

    const svg = coverSvg(a.slug, a.titulo)
    const png = await sharp(Buffer.from(svg)).png().toBuffer()
    const asset = await client.assets.upload("image", png, {
      contentType: "image/png",
      filename: `${a.slug}-cover.png`,
    })

    const doc = {
      _type: "articulo",
      titulo: a.titulo,
      slug: { _type: "slug", current: a.slug },
      descripcion: a.descripcion,
      portada: { _type: "image", asset: { _type: "reference", _ref: asset._id } },
      fecha: a.fecha,
      autor: "PixelArch",
      tags: a.tags,
      contenido: blocks(a.contenido),
      meta_title: a.meta_title,
      meta_description: a.meta_description,
      og_image: { _type: "image", asset: { _type: "reference", _ref: asset._id } },
      activo: true,
    }

    await client.create(doc)
    console.log(`OK    ${a.slug} — ${a.titulo}`)
  }

  console.log("\nListo. Revisa https://pixelarch.dev/blog")
}

run().catch((e) => {
  console.error("Error:", e)
  process.exit(1)
})